// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSTGQT1cndkqKs0HA0ERIvbSg5Vfra2zk',
    appId: '1:535380296750:web:c7ba3e7a4d87b7e602cbbf',
    messagingSenderId: '535380296750',
    projectId: 'cryptotracker-auth',
    authDomain: 'cryptotracker-auth.firebaseapp.com',
    storageBucket: 'cryptotracker-auth.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBf0BxkWhnn1kGYJ6jYLb8rO7H3mgp7b6g',
    appId: '1:535380296750:android:a2d744da83bbedaf02cbbf',
    messagingSenderId: '535380296750',
    projectId: 'cryptotracker-auth',
    storageBucket: 'cryptotracker-auth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzVWUcLUoZmjoGfk4NByG7DcAOF02v7GQ',
    appId: '1:535380296750:ios:ac34db04dbe354bd02cbbf',
    messagingSenderId: '535380296750',
    projectId: 'cryptotracker-auth',
    storageBucket: 'cryptotracker-auth.appspot.com',
    iosClientId: '535380296750-q59okt152aq36b17rav95gm4hf07g844.apps.googleusercontent.com',
    iosBundleId: 'com.example.cryptotrackerUpdated',
  );
}
